# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - gsl_win
  pull_request:
    branches:
    - gsl_win
      

# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          #- {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Chmod configure and cleanup
        run: |
          export TMPDIR=~/tmp && \
          chmod +x configure && \
          chmod +x cleanup 

      - name: Bootstrap
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap
      - name: Dependencies
        run: ./run.sh install_deps

      - name: Test
        run: ./run.sh run_tests

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./run.sh coverage
        